import os
import re
from pathlib import Path
from rich.console import Console
from rich.panel import Panel

from ..core.roadbook import RoadbookManager
from ..core.runtime import RuntimeManager
from ..utils.output import console, print_error, print_success
from . import editor
import argparse

def _generate_id(name: str) -> str:
    """Generate a valid ID from the roadbook name."""
    # Convert to lowercase
    id_str = name.lower()
    # Replace spaces and underscores with hyphens
    id_str = re.sub(r'[\s_]+', '-', id_str)
    # Remove any non-alphanumeric characters except hyphens
    id_str = re.sub(r'[^a-z0-9\-]', '', id_str)
    # Remove duplicate hyphens
    id_str = re.sub(r'-+', '-', id_str)
    # Strip leading/trailing hyphens
    id_str = id_str.strip('-')
    return id_str

def init_book(args):
    """Initialize a new roadbook scaffold."""
    name = args.name
    description = args.description
    goal = args.goal
    
    rb_id = _generate_id(name)
    if not rb_id:
        print_error("Invalid roadbook name. Cannot generate a valid ID.")
        return
        
    # Check for duplicates
    existing_books = RoadbookManager.list_roadbooks()
    for book in existing_books:
        if book.id == rb_id:
            print_error(f"A roadbook with ID '{rb_id}' already exists at {book.path.parent}.")
            return

    # Create directory structure in current workspace
    cwd = Path.cwd()
    
    # Priority: .roadbook in CWD, creating if not exists
    work_dir = cwd / ".roadbook"
    book_dir = work_dir / rb_id
    
    try:
        if not work_dir.exists():
            print(f"Initializing .roadbook directory at {work_dir}")
        book_dir.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        print_error(f"Failed to create directory {book_dir}: {e}")
        return

    # 1. Generate roadbook.md
    roadbook_path = book_dir / "roadbook.md"
    
    # Base YAML frontmatter
    yaml_frontmatter = f"""---
id: "{rb_id}"
name: "{name}"
version: "1.0"
description: "{description}"
tags: []
inputs: 
  target_url: 
    description: "The starting URL"
    default: "https://www.google.com"
outputs: {{}}
---
"""
    
    if goal:
        # Autonomous exploration scaffold
        content = f"""{yaml_frontmatter}
## 目标定义 (Goal)
**ID**: goal1
**Description**: {goal}

> 请 AI Agent 基于上述目标进行自主探索。探索成功后，请将有效步骤提取并覆盖到本文件中。
"""
    else:
        # Human-guided scaffold
        content = f"""{yaml_frontmatter}
## 初始化 (Initialization)
**ID**: init
**Description**: 初始化浏览器并导航到目标页面
**URL**: `{{{{target_url}}}}`

**Steps**:
1. GOTO "{{{{target_url}}}}"

---

## 业务流程 (Main Flow)
**ID**: main
**Description**: [请在此处描述具体的业务操作流程]

**Steps**:
1. [请填写具体步骤，例如: `CLICK "#search-btn"`]
2. [补充后续步骤]
"""

    try:
        with open(roadbook_path, "w", encoding="utf-8") as f:
            f.write(content)
    except Exception as e:
        print_error(f"Failed to write roadbook.md: {e}")
        return

    # 2. Generate script scaffold
    scripts_dir = RuntimeManager.get_scripts_dir(rb_id, book_dir=book_dir)
    
    # ensure subdirectories exist
    (scripts_dir / "tests").mkdir(parents=True, exist_ok=True)
    (scripts_dir / "utils").mkdir(parents=True, exist_ok=True)
    
    # Create __init__.py for utils
    with open(scripts_dir / "utils" / "__init__.py", "w") as f:
        pass

    # 2.1 Generate utils/browser.py (Modular connection logic)
    browser_utils_path = scripts_dir / "utils" / "browser.py"
    browser_utils_content = '''"""
Browser configuration and initialization utilities.
"""
from playwright.sync_api import sync_playwright, Browser, BrowserContext, Page
import logging

def get_playwright_context(headless=False):
    """
    Standard context manager for Playwright.
    """
    p = sync_playwright().start()
    
    # --- Browser Launch Strategies ---
    
    # Strategy 1: Fresh Browser (Default)
    # Best for: Clean state, reproducible runs, CI/CD, and initial exploration.
    browser = p.chromium.launch(headless=headless)
    
    # Strategy 2: Connect to Existing Browser (CDP)
    # Best for: Debugging, reusing login state, avoiding bot detection.
    # To use: 
    # 1. Run Chrome with: --remote-debugging-port=9222
    # 2. Uncomment line below:
    # browser = p.chromium.connect_over_cdp("http://localhost:9222")
    
    context = browser.new_context()
    page = context.new_page()
    return p, browser, context, page
'''
    try:
        with open(browser_utils_path, "w", encoding="utf-8") as f:
            f.write(browser_utils_content)
    except Exception as e:
        print_error(f"Failed to write utils/browser.py: {e}")

    # 2.2 Generate script.py
    script_path = scripts_dir / "script.py"
    
    script_content = f'''"""
Automation script for roadbook: {name} ({rb_id})
Generated by Roadbook CLI.
"""
import sys
import json
import logging
import time
from pathlib import Path

# Add current directory to path so we can import utils
sys.path.append(str(Path(__file__).parent))

from utils.browser import get_playwright_context

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

def run(inputs: dict) -> dict:
    """
    Main execution entry point.
    """
    logger.info(f"Starting execution for {{inputs}}")
    
    try:
        # Initialize Browser using shared utility
        p, browser, context, page = get_playwright_context(headless=False)
        
        try:
            # TODO: Implement automation steps here
            # Example: 
            # target_url = inputs.get("target_url", "https://example.com")
            # page.goto(target_url)
            # logger.info(f"Navigated to {{target_url}}")
            
            logger.info("Steps completed successfully")
            
        finally:
            browser.close()
            p.stop()
            
        return {{"status": "success", "data": {{}}}}

    except Exception as e:
        logger.error(f"Execution failed: {{e}}", exc_info=True)
        return {{"status": "failed", "error": str(e)}}

if __name__ == "__main__":
    # Standard Entry Point for CLI Execution
    try:
        # Load inputs from stdin if available, else empty dict
        if len(sys.argv) > 1 and sys.argv[1].startswith("{{"):
             cli_inputs = json.loads(sys.argv[1])
        else:
             cli_inputs = {{}}
        
        result = run(cli_inputs)
        
        # Ensure result is printed to stdout for capture
        print(json.dumps(result))
        
    except Exception as e:
        print(json.dumps({{"status": "failed", "error": str(e)}}))
        sys.exit(1)
'''
    
    try:
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)
    except Exception as e:
        print_error(f"Failed to write script.py: {e}")
        return

    # Success output with feedback prompt for AI agent
    print_success(f"Successfully initialized roadbook scaffold for '{name}' (ID: {rb_id})")
    console.print(f"Directory: [cyan]{book_dir}[/cyan]")
    
    # Handle auto-edit
    if args.edit:
        console.print("[bold cyan]Launching Roadbook Editor...[/bold cyan]")
        # Construct arguments for editor
        editor_args = argparse.Namespace(
            port=8000, 
            host="127.0.0.1", 
            dir=str(book_dir),
            id=rb_id
        )
        editor.start_editor(editor_args)
        return

    # Constructing AI Agent feedback prompt
    feedback_lines = [
        f"路书脚手架已生成在 {book_dir} 目录下。"
    ]
    
    if goal:
        feedback_lines.extend([
            "模式：[AI 自主探索模式]",
            "下一步建议：",
            "1. 请阅读并分析 `roadbook.md` 中的目标 (Goal)。",
            "2. 开始编写或修改 `scripts/script.py`，使用 playwright 等工具探索如何达成目标。",
            "3. 探索成功后，请清洗执行路径，将有效的 AARP 动作原语回写到 `roadbook.md` 中，完善路书本体。"
        ])
    else:
        feedback_lines.extend([
            "模式：[人机协同/手动引导模式]",
            "下一步建议：",
            "1. 请用户或 AI 代理优先修改 `roadbook.md`，填充具体的 Sheet（场景）信息。",
            "2. 推荐使用编辑器：运行 `roadbook edit {rb_id}` 启动可视化编辑器。",
            "3. 在编辑器中，你可以使用截图工具上传图片，并使用涂鸦功能进行标注。",
            "4. 当 `roadbook.md` 描述清晰后，可将其翻译为 `scripts/script.py` 中的具体执行代码。"
        ])
        
    feedback_text = "\n".join(feedback_lines)
    console.print(Panel(feedback_text, title="[bold yellow]🤖 给 AI Agent 的后续引导[/bold yellow]", border_style="yellow"))
