"""
Automation script for roadbook: {name} ({rb_id})
Generated by Roadbook CLI at {date_str}.

[AGENT INSTRUCTION - BEST PRACTICES]
1. Schema Sync [CRITICAL]: Modify the `TaskInput` and `TaskOutput` Pydantic models below to define your data contract. DO NOT manually edit `input_schema.json` or `output_schema.json` - they are generated automatically from these models.
2. Target URL: Target URLs are usually fixed for a specific task. Hardcode them in the script (e.g., `page.goto("https://...")`) instead of passing via `TaskInput` unless the script is explicitly designed for multiple domains.
3. State Passing: To pass variables between phase functions, add fields to the `TaskState` Pydantic model and access them via `rb.state`. Use `rb.storage` for managing files and downloads.
4. Selectors: Prefer semantic locators (e.g., `page.get_by_role()`, `page.get_by_text()`) over brittle XPath/CSS.
5. Authentication: Use `rb.auth.ensure_login(mode=AuthMode.LONG_LIVED, verify_selector="...", entry_url="...", debug=True)` to handle login flexibly.
6. Human Intervention: Use `rb.wait_for_condition(success_selector="...", message="...")` for auto-resuming waits, or `rb.pause_for_manual_action(message="...")` for terminal confirmation.

[AGENT INSTRUCTION - AARP TRANSLATION GUIDE]
When translating roadbook.md steps to Playwright Python:
- GOTO url -> page.goto(url)
- CLICK selector -> page.locator(selector).click()
- INPUT selector value -> page.locator(selector).fill(value)
- WAIT time/selector -> page.wait_for_timeout(ms) or page.locator(selector).wait_for()
- EXTRACT selector -> text = page.locator(selector).text_content()
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from roadbook.sdk import RoadbookContext
from roadbook.sdk.auth import AuthMode

# ==========================================
# 📋 I/O Contracts (Single Source of Truth)
# [AGENT INSTRUCTION] Update these models based on the user's requirements.
# ==========================================

class TaskInput(BaseModel):
    """Input parameters for the task"""
{input_model_fields}

class TaskOutput(BaseModel):
    """Extracted data structure"""
{output_model_fields}

class TaskState(BaseModel):
    """
    Internal state for passing variables between phase functions.
    Add fields here as you discover them during exploration.
    """
    pass

# ==========================================
# ⚙️ Phase Functions
# ==========================================

{phase_functions}

# ==========================================
# 🙋‍♂️ Authentication Example (Optional)
# ==========================================
# def phase_handle_login(rb: RoadbookContext, inputs: TaskInput):
#     with rb.sheet("handle_login"):
#         # Use built-in auth manager to handle various login scenarios
#         rb.auth.ensure_login(
#             mode=AuthMode.LONG_LIVED,  # Change to ANTI_BOT_INTERACTIVE if CDP blocks login
#             verify_selector=".user-profile-icon", # Selector that proves we are logged in
#             entry_url="https://example.com/login",
#             debug=True
#         )
#
#         # Optional: use snapshot diffing to detect state changes
#         # rb.auth.snapshot_state("pre_login")
#         # ... login actions ...
#         # rb.auth.snapshot_state("post_login")
#         # diff = rb.auth.diff_states("pre_login", "post_login")
#         # rb.logger.info(f"New elements after login: {diff['appeared']}")

# ==========================================
# 🚀 Main Execution
# ==========================================

def run():
{site_constraints_block}
    
    # Context manages everything automatically: ephemeral browsers, storage state saving/loading.
    with RoadbookContext(rb_id="{rb_id}", site_overrides=site_constraints) as rb:
        # Bind Pydantic models so the SDK can auto-generate JSON schemas and validate outputs
        rb.bind_schemas(input_model=TaskInput, output_model=TaskOutput)
        
        try:
            # 1. Parse and validate inputs
            raw_inputs = rb.get_inputs()
            inputs = TaskInput(**raw_inputs)
            
            # 2. State management for passing variables between phases
            rb.state = TaskState()
            
            # 3. Execute phases sequentially
{phase_calls}
            
            rb.logger.info("🎉 All sheets completed successfully.")
            
        except Exception as e:
            rb.logger.error(f"❌ Task failed: {e}")
            raise

if __name__ == "__main__":
    run()
